### ISSUE TITLE
Make the browser hung 

### ISSUE THREAD

**Issue by hyzhang6639** [yannickebongue/ngx-material-time-select#2]
I add the below code in template html 

<input [matTimeSelect]="myTimeSelect">
<mat-time-select #myTimeSelect></mat-time-select>

The page can't be loaded and the below errors are flooded in the console log of the Chrome browser.

StaticInjectorError(AppModule)[TimeAdapter -> DateAdapter]: 
  StaticInjectorError(Platform: core)[TimeAdapter -> DateAdapter]: 
    NullInjectorError: No provider for DateAdapter!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (core.js:8894)
    at resolveToken (core.js:9139)
    at tryResolveToken (core.js:9083)

**Comment by yannickebongue** [comment]
This is because the TimeAdapter extends the DateAdapter defined in MatDatepickerModule.

For now you have to import explicitly the following modules:

- `MatDatepickerModule from @angular/material`
- `MatNativeDateModule from @angular/material` or `MatMomentDateModule from @angular/material-moment-adapter`

Note: The time adapter implementation must correspond to the date adapter implementation. So if you use the `MatNativeTimeModule` you must import `MatNativeDateModule`. If you use `MatMomentTimeModule` you must import `MatMomentDateModule`.
